/*
 * generated by Xtext 2.11.0
 */
package org.learning.example.ui.wizard;

import org.eclipse.xtext.ui.wizard.XtextNewProjectWizard;

import org.eclipse.xtext.ui.wizard.IExtendedProjectInfo;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import com.google.inject.Inject;

public class MyDslNewProjectWizard extends XtextNewProjectWizard {

	private MyDslWizardNewProjectCreationPage mainPage;

	@Inject
	public MyDslNewProjectWizard(IProjectCreator projectCreator) {
		super(projectCreator);
		setWindowTitle("New MyDsl Project");
	}

	protected MyDslWizardNewProjectCreationPage getMainPage() {
		return mainPage;
	}

	/**
	 * Use this method to add pages to the wizard.
	 * The one-time generated version of this class will add a default new project page to the wizard.
	 */
	@Override
	public void addPages() {
		mainPage = createMainPage("basicNewProjectPage");
		mainPage.setTitle("MyDsl Project");
		mainPage.setDescription("Create a new MyDsl project.");
		addPage(mainPage);
	}

	protected MyDslWizardNewProjectCreationPage createMainPage(String pageName) {
		return new MyDslWizardNewProjectCreationPage(pageName);
	}

	/**
	 * Use this method to read the project settings from the wizard pages and feed them into the project info class.
	 */
	@Override
	protected IExtendedProjectInfo getProjectInfo() {
		MyDslProjectInfo projectInfo = new MyDslProjectInfo();
		projectInfo.setProjectName(mainPage.getProjectName());
		if (!mainPage.useDefaults()) {
			projectInfo.setLocationPath(mainPage.getLocationPath());
		}
		return projectInfo;
	}

}
