/*
 * generated by Xtext 2.11.0
 */
package org.learning.example.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class MyDslProjectInfo extends DefaultProjectInfo {

}
