/*
 * generated by Xtext 2.11.0
 */
package org.learning.example.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class MyDslWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public MyDslWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
